### PR TITLE
Added spanish translation and changed text domain

### PR DESCRIPTION
**Pull request by davidperezgar**
I've added spanish translation and changed textdomain to pixproof that you have already set but not put it in _e and __ strings. I've added in views a text translatable.

All these fixes are to put available to translate the plugin.

### CODE REVIEW

**Comment by andreilupu** [comment]
thank you for your contribution, we will soon push and update on wordpress.org.

**Comment by davidperezgar** [comment]
Ok Nice. I couldn't translated the Javascript file that makes the gallery (Strings like 'Select' and Deselect and 'of'). Do you know how to make it localizable?

**Comment by andreilupu** [comment]
I'll take care of it

**Comment by davidperezgar** [comment]
Thanks Andreil

**Pull request merged**
