### PR TITLE
Finished the translation in Spanish 100%

### PR DESCRIPTION
**Pull request by davidperezgar**
Hello, I've finished and shared with you the translation in spanish.

It's still missing the Javascript as we can see in next revisions.

Regards.

### CODE REVIEW

**Comment by raduconst** [comment]
We choose not to include the po/mo files anymore inside the plugin. Even that, you can add the translations for PixProof on this page: https://translate.wordpress.org/projects/wp-plugins/pixproof
This way, anyone who will download the plugin, will have the pot file and maybe he doesn't want to translate the plugin. But, if that user will want to translate the plugin, once you added the right translations on wordpress.org, it will be able to use your files (or make his own translations).

**Comment by davidperezgar** [comment]
Ok I agree, but I cannot upload the translation in po file if I'm not an editor.... It need it.

**Comment by raduconst** [comment]
Even if you are not an editor of the plugin (neither am I), you can suggest translations.   I will download your files and try to include them by myself. Thanks again for your help :-) (and we'll love your help on our other plugins, when you'll have some free time)

**Comment by davidperezgar** [comment]
Yes, that's the issue that I don't understand in Glotpress wordpress. You cannot upload po files already translated if you are not editor, but it's not clear where you can make an editor or who can make it... anyway... yes, i'll see your plugins! regards!

**Pull request closed without merging**
